In [1]:
import pandas as pd
import numpy as np

In [2]:
df_laptops=pd.read_csv('laptops.csv')
df_laptops.head(3)

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.0
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.0
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.0

In [3]:
#Find rows which have 'Apple' in the 'Brand' column
df_laptops['Brand']=='Asus'

#Filter Dataframe based on condition
df_laptops[df_laptops['Brand']=='Asus'].value_counts('Brand')

Brand
Asus    415
Name: count, dtype: int64

In [4]:
#EXERCISE 1:
#Find rows which dont have 'HP' in the 'Brand' column
df_laptops['Brand']!='HP'

#Filter dataframe based on condition
df_laptops[df_laptops['Brand']!='HP'].value_counts('Brand')

Brand
Asus                415
Lenovo              366
MSI                 308
Acer                137
Apple               116
Dell                 84
Microsoft            77
Gigabyte             48
Razer                37
Medion               32
LG                   32
Alurin               29
PcCom                24
Samsung              22
Dynabook Toshiba     19
Vant                 11
Primux                8
Deep Gaming           8
Innjoo                6
Thomson               4
Prixton               3
Millenium             2
Denver                1
Jetwing               1
Realme                1
Toshiba               1
Name: count, dtype: int64

In [5]:
#EXERCISE 2:
#Find laptops with Final Price over 2000

df_laptops[df_laptops['Final Price'] > 2000].value_counts('Brand')

Brand
MSI          105
Asus          69
Lenovo        38
Razer         32
Apple         26
Microsoft     20
HP            19
Gigabyte      14
Acer          11
Dell           9
LG             8
Samsung        6
Medion         3
Millenium      1
Name: count, dtype: int64

# Create a Column Based on 1 Condition: np.where()

In [6]:
#create an array based on price tiers
#np.where(df_laptops['Final Price']>2000,'Expensive','Cheap')

#Set it into a new Column
df_laptops['Price Tier'] = np.where(df_laptops['Final Price']>2000,'Expensive','Cheap')
df_laptops.value_counts('Price Tier')
df_laptops.head()

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price,Price Tier
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00,Cheap
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00,Cheap
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00,Cheap
3,MSI Katana GF66 12UC-082XES Intel Core i7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.00,Cheap
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01,Cheap

In [7]:
#EXERCISE 1
#create an array based on Screen
#np.where(df_laptops['Screen']>14.0,'Big','Small')

df_laptops['Screen Size']=np.where(df_laptops['Screen']>14.0,'Big','Small')
df_laptops.value_counts('Screen Size')

Screen Size
Big      1506
Small     654
Name: count, dtype: int64

# Filer dataframe based on multiple conditions

In [8]:
#Find Apple laptops that costs more than 2000
(df_laptops['Brand']=='Apple') & (df_laptops['Final Price']>2000)


df_laptops[(df_laptops['Brand']=='Apple') & (df_laptops['Final Price']>2000)]

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price,Price Tier,Screen Size
295,Apple MacBook Pro Apple M2 Pro 10 Núcleos/16GB...,New,Apple,MacBook Pro,Apple M2 Pro,16,512,SSD,NaN,14.2,No,2209.00,Expensive,Big
360,Apple MacBook Pro Apple M2 Pro 10 Núcleos/16GB...,New,Apple,MacBook Pro,Apple M2 Pro,16,512,SSD,NaN,14.2,No,2269.00,Expensive,Big
416,Apple MacBook Pro Apple M1 Max/32GB/1TB SSD/16...,New,Apple,MacBook Pro,Apple M1,32,1000,SSD,NaN,16.2,No,3849.00,Expensive,Big
500,Apple MacBook Pro Apple M2 Max/32GB/1TB SSD/16...,New,Apple,MacBook Pro,Apple M2,32,1000,SSD,NaN,16.2,No,3799.00,Expensive,Big
501,Apple MacBook Pro Apple M2 Max/32GB/1TB SSD/14...,New,Apple,MacBook Pro,Apple M2,32,1000,SSD,NaN,14.2,No,3379.01,Expensive,Big
510,Apple MacBook Pro Apple M2 Pro 12 Núcleos/16GB...,New,Apple,MacBook Pro,Apple M2 Pro,16,1000,SSD,NaN,14.2,No,2729.01,Expensive,Big
532,Apple MacBook Pro Apple M2 Pro 10 Núcleos/32GB...,New,Apple,MacBook Pro,Apple M2 Pro,32,512,SSD,NaN,14.2,No,2719.00,Expensive,Big
538,Apple MacBook Pro Apple M2 Pro 10 Núcleos/32GB...,New,Apple,MacBook Pro,Apple M2 Pro,32,1000,SSD,NaN,14.2,No,2939.01,Expensive,Big
556,Apple MacBook Pro Apple M2 Pro 12 Núcleos/16GB...,New,Apple,MacBook Pro,Apple M2 Pro,16,512,SSD,NaN,16.2,No,2729.01,Expensive,Big
583,Apple MacBook Pro Apple M2 Pro 12 Núcleos/32GB...,New,Apple,MacBook Pro,Apple M2 Pro,32,1000,SSD,NaN,16.2,No,3499.01,Expensive,Big
631,Apple MacBook Pro Apple M2 Pro 12 Núcleos/16GB...,New,Apple,MacBook Pro,Apple M2 Pro,16,1000,SSD,NaN,16.2,No,2999.01,Expensive,Big
665,Apple MacBook Pro Apple M2 Pro 12 Núcleos/16GB...,New,Apple,MacBook Pro,Apple M2 Pro,16,1000,SSD,NaN,14.2,No,2749.00,Expensive,Big
667,Apple MacBook Pro Apple M2 Pro 12 Núcleos/16GB...,New,Apple,MacBook Pro,Apple M2 Pro,16,512,SSD,NaN,16.2,No,2789.00,Expensive,Big
683,Apple MacBook Pro Apple M2 Max/32GB/1TB SSD/14...,New,Apple,MacBook Pro,Apple M2,32,1000,SSD,NaN,14.2,No,3399.00,Expensive,Big
725,Apple MacBook Pro Apple M2 Pro 12 Núcleos/32GB...,New,Apple,MacBook Pro,Apple M2 Pro,32,1000,SSD,NaN,14.2,No,3279.00,Expensive,Big
742,Apple MacBook Pro Apple M2 Pro 12 Núcleos/32GB...,New,Apple,MacBook Pro,Apple M2 Pro,32,512,SSD,NaN,16.2,No,3279.00,Expensive,Big
870,Apple MacBook Pro Apple M2 Pro 12 Núcleos/16GB...,New,Apple,MacBook Pro,Apple M2 Pro,16,1000,SSD,NaN,16.2,No,2999.01,Expensive,Big
1026,Apple MacBook Pro Apple M1 Pro/16GB/1TB SSD/14...,Refurbished,Apple,MacBook Pro,Apple M1 Pro,16,1000,SSD,NaN,14.2,No,2749.00,Expensive,Big
1052,Apple Macbook Pro Intel Core i9/32GB/2TB SSD/R...,Refurbished,Apple,MacBook Pro,Intel Core i9,32,2000,SSD,Radeon Pro 5500M,16.0,No,2755.00,Expensive,Big
1133,Apple MacBook Pro Apple M1 Pro/16GB/1TB SSD/14...,Refurbished,Apple,MacBook Pro,Apple M1 Pro,16,1000,SSD,NaN,14.2,No,2749.00,Expensive,Big
1744,Apple MacBook Pro 2021 Apple M1 Pro/16GB/1TB S...,Refurbished,Apple,MacBook Pro,Apple M1 Pro,16,1000,SSD,NaN,14.2,No,2500.01,Expensive,Big
1745,Apple MacBook Pro Apple M1 Pro/16GB/1TB SSD/16...,Refurbished,Apple,MacBook Pro,Apple M1 Pro,16,1000,SSD,NaN,16.2,No,2979.00,Expensive,Big
1746,Apple MacBook Pro Apple M1 Pro/16GB/1TB SSD/16...,Refurbished,Apple,MacBook Pro,Apple M1 Pro,16,1000,SSD,NaN,16.2,No,2950.00,Expensive,Big
1747,Apple MacBook Pro Apple M1 Pro/16GB/512GB SSD/...,Refurbished,Apple,MacBook Pro,Apple M1 Pro,16,512,SSD,NaN,14.2,No,2500.01,Expensive,Big
1748,Apple MacBook Pro Apple M1 Pro/32GB/1TB SSD/14...,Refurbished,Apple,MacBook Pro,Apple M1 Pro,32,1000,SSD,NaN,14.2,No,2500.01,Expensive,Big
1770,Apple Macbook Pro Intel Core i9/32GB/2TB SSD/R...,Refurbished,Apple,MacBook Pro,Intel Core i9,32,2000,SSD,Radeon Pro 5500M,16.0,No,2711.40,Expensive,Big

In [9]:
#Apple or Dell laptops
df_laptops[(df_laptops['Brand']=='Apple') | (df_laptops['Brand']=='Dell')]
df_laptops[(df_laptops['Brand']=='Apple') | (df_laptops['Brand']=='Dell')].value_counts('Brand')

Brand
Apple    116
Dell      84
Name: count, dtype: int64

In [10]:
#Laptop from Apple or Dell that costs over 2000
df_laptops[((df_laptops['Brand']=='Apple') | (df_laptops['Brand']=='Dell')) & (df_laptops['Final Price']>2000)]
df_laptops[((df_laptops['Brand']=='Apple') | (df_laptops['Brand']=='Dell')) & (df_laptops['Final Price']>2000)].value_counts('Brand')

Brand
Apple    26
Dell      9
Name: count, dtype: int64